name: Update README

on:
  workflow_dispatch:
  schedule:
    # 1時間ごとに実行
    - cron: '0 */1 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Qiita feed
        uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://qiita.com/SabaCrevette/feed.atom' # 例: 'https://qiita.com/your-username/feed.atom'
          file: 'README.md'
      - name: Commit and push if changed
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update README with latest Qiita posts" || true
          git push
